#writes it to your directory with music
music_directory     "/mnt/c/Users/cjcra/Documents/personal/music"

playlist_directory  "/home/carterdelar1/.config/mpd/playlists"
db_file             "/home/carterdelar1/.config/mpd/database"
log_file            "/home/carterdelar1/.config/mpd/log"
pid_file            "/home/carterdelar1/.config/mpd/pid"
state_file          "/home/carterdelar1/.config/mpd/state"

bind_to_address     "127.0.0.1"
port                "6600"

audio_output {
    type            "pulse"
    name            "WSL Audio"
}
